### ISSUE TITLE
duplicate of https://github.com/OCA/odoo-module-migrator ?

### ISSUE THREAD

**Issue by legalsylvain** [OCA/oca-port#1]
Hi. 

reading the description, it seems that it is a duplicate of the current https://github.com/OCA/odoo-module-migrator tools. Is in't it ?

**Comment by sbidoul** [comment]
@sebalix @simahawk

**Comment by simahawk** [comment]
Please check this https://github.com/OCA/maintainer-tools/pull/504#issuecomment-893354771

**Comment by legalsylvain** [comment]
thanks @simahawk.
