### ISSUE TITLE
`InputStore`: store module and PRs to blacklist in one file per module

### ISSUE THREAD

**Issue by sebalix** [OCA/oca-port#4]
### Context
Currently all these data are stored in one file, but the goal would be to store these information in the Git repository to share them with other contributors (if we decide to blacklist a PR or to not port an addon to a version, we don't want to be annoyed with this anymore).

### TODO

To ease this sharing, better to avoid conflicts on one global file and improve the readability by splitting it with one file per module. Knowing that this file will be stored on the source branch:
```js
# File '.oca-port/blacklist/shopfloor.json' on 14.0 branch
{
    "pull_requests": {
        "13.0": [
            299    # Do not port PR #299 from 14.0 to 13.0
        ],
        "15.0": [
            312    # Do not port PR #312 from 14.0 to 15.0
        ]
    },
    "no_migration": {
        "12.0": true    # Do not migrate this module from 14.0 to 12.0
    }
}
```
Maybe the `no_migration` key should be stored in the target branch, to indicate we don't want this module on this version, without taking into account the source branch:
```js
# File .oca-port/blacklist/'shopfloor.json' on X.Y branch
{
    "no_migration": true    # Do not migrate this module on this version
}
```
:thinking:

**Comment by simahawk** [comment]
Seems a good idea.
