### ISSUE TITLE
Change pre-commit git message

### ISSUE THREAD

**Issue by sbidoul** [OCA/oca-port#45]
This commit message is not accurate anymore

https://github.com/OCA/oca-port/blob/8dbef28896824ff6a29b62dacfccc2d5fd6f23e2/oca_port/utils/git.py#L256-L258

because pre-commit does a lot of other things, and, in v17, does not use black and isort at all.

Suggestion: `[IMP] apply pre-commit auto fixes`

**Comment by sbidoul** [comment]
I'm neutral on this. Strictly speaking, during a migration only the migrated module should be touched by pre-commit if the rest did not change.

**Comment by sebalix** [comment]
Yes, the git format-patch will include commits of the module, nothing else so only related files should be updated by pre-commit, I'll re-introduce the name of the module in the commit message then.
Thank you for the followup.
