### ISSUE TITLE
views_migration_17: Integrate into oca-port?

### ISSUE THREAD

**Issue by CRogos** [OCA/oca-port#49]
**Is your feature request related to a problem?**
feature request
Would it be possible to integrate views_migration_17 into oca-port? 
https://github.com/OCA/server-tools/tree/17.0/views_migration_17

**Comment by sebalix** [comment]
Hello @CRogos ,

`oca-port` has no goal to migrate the code of modules, and only deals with git history to make comparison of what is missing from one branch to another.

For the migration of the code itself, your suggestion would have its place in another tool I suppose: https://github.com/OCA/odoo-module-migrator
Later I would like to call the later from `oca-port` so the code will be automatically migrated when porting stuff (both software could be complementary).
