### ISSUE TITLE
pypi publishing

### ISSUE THREAD

**Issue by rousseldenis** [OCA/oca-port#5]
@sebalix @sbidoul Do you plan to publish it on pypi ?

**Comment by sbidoul** [comment]
I made #6 with the publishing workflow and version inference from git tags.

@sebalix do you want to add more metadata in setup.cfg (include README from file, license, author, etc)? I'll then push the first release and finalize the CI configuration.

After that publishing a release will be a matter of creating a GitHub release with git tag.

**Comment by simahawk** [comment]
@sebalix ping

**Comment by flagreenice** [comment]
I can't find the library in pypi. Is it uploaded or am I missing something?

**Comment by sbidoul** [comment]
I just published to PyPI: https://pypi.org/project/oca-port/

The publish token is also set-up in GitHub actions, to the next time a tag of the form vX.Y.Z is created, it should be published automatically.

**Comment by flachica** [comment]
Great work, thanks a lot
